### ISSUE TITLE
Cant download anything

### ISSUE THREAD

**Issue by kagami777** [fgRuslan/BooruDownloader#6]
when I try and download from danbooru I get a (403) Forbidden error. When I try to download from gelbooru I get an unhandled exception. It wont let me download anything.

**Comment by ShujianDou** [comment]
Probably an issue relating to headers? What's the url to the site, which you're trying to download from?

**Comment by fgRuslan** [comment]
I tried to replicate this and I also got 403. I'm gonna try to work on it soon.

**Comment by fgRuslan** [comment]
I'm close to fixing this I guess. I have also fixed some minor issues within the code and did a cleanup. Gonna push as soon as I fix this.
