### ISSUE TITLE
download interrupted（503）

### ISSUE THREAD

**Issue by bush-21** [fgRuslan/BooruDownloader#7]
Sometimes I get aborted when downloading images due to network issues. For example, I want to download 1000 pictures. When I finish downloading 200 pictures, the download is interrupted. If I choose to continue downloading, it will waste time to download the first 200 pictures repeatedly. Is there any way to solve this?

**Comment by fgRuslan** [comment]
I think I'm gonna add an option to set an offset, this will be helpful in your case.

**Comment by bush-21** [comment]
您好，邓世龙已收到您的邮件，将尽快处理。
